### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by willprice** [MVSE-Outreach/unknownsoftware-animation-workshop#1]
FYI so far we've used the nomenclature <tech>-<project name> for naming projects so it's easy to see what projects/workshops we've got for each activity on the MVSE-outreach organisation. It'd be nice to have this as `pencil2d-animation-workshop`, but up to you :)

**Comment by LukeStorry** [comment]
Right thanks, it was only a note to remind me to finish it later, I'll
change the name when I get back to a pc
